name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog - we'll create one later
          # changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          # TODO: Enable other platforms after OpenSSL issue is resolved
          # - target: x86_64-unknown-linux-gnu
          #   os: ubuntu-latest
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fpm
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          include: LICENSE,README.md
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
